// <auto-generated />
using System;
using ApiCoffeeTea.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ApiCoffeeTea.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApiCoffeeTea.Data.address", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("id"));

                    b.Property<string>("city")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("is_default")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("line1")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("postal_code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("user_id")
                        .HasColumnType("integer");

                    b.HasKey("id")
                        .HasName("addresses_pkey");

                    b.HasIndex("user_id");

                    b.ToTable("addresses");
                });

            modelBuilder.Entity("ApiCoffeeTea.Data.article", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("id"));

                    b.Property<int?>("category_id")
                        .HasColumnType("integer");

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("cover_image_url")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("is_published")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("published_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("summary")
                        .HasColumnType("text");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("id")
                        .HasName("articles_pkey");

                    b.HasIndex("category_id");

                    b.HasIndex(new[] { "slug" }, "articles_slug_key")
                        .IsUnique();

                    b.ToTable("articles");
                });

            modelBuilder.Entity("ApiCoffeeTea.Data.article_category", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("id"));

                    b.Property<bool>("deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("id")
                        .HasName("article_categories_pkey");

                    b.HasIndex(new[] { "name" }, "article_categories_name_key")
                        .IsUnique();

                    b.ToTable("article_categories");
                });

            modelBuilder.Entity("ApiCoffeeTea.Data.audit_log", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("id"));

                    b.Property<DateTime>("changed_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("new_values")
                        .HasColumnType("jsonb");

                    b.Property<string>("old_values")
                        .HasColumnType("jsonb");

                    b.Property<string>("operation")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("row_id")
                        .HasColumnType("integer");

                    b.Property<string>("table_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("user_id")
                        .HasColumnType("integer");

                    b.HasKey("id")
                        .HasName("audit_log_pkey");

                    b.HasIndex("user_id");

                    b.ToTable("audit_log");
                });

            modelBuilder.Entity("ApiCoffeeTea.Data.cart", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("id"));

                    b.Property<DateTime>("added_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<decimal>("price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("product_id")
                        .HasColumnType("integer");

                    b.Property<int>("quantity")
                        .HasColumnType("integer");

                    b.Property<int>("user_id")
                        .HasColumnType("integer");

                    b.HasKey("id")
                        .HasName("cart_pkey");

                    b.HasIndex("product_id");

                    b.HasIndex(new[] { "user_id" }, "ix_cart_user_id");

                    b.HasIndex(new[] { "user_id", "product_id" }, "ux_cart_user_product_not_deleted")
                        .IsUnique()
                        .HasFilter("(deleted = false)");

                    b.ToTable("cart", (string)null);
                });

            modelBuilder.Entity("ApiCoffeeTea.Data.category", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("id"));

                    b.Property<bool>("deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("parent_id")
                        .HasColumnType("integer");

                    b.HasKey("id")
                        .HasName("categories_pkey");

                    b.HasIndex("parent_id");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("ApiCoffeeTea.Data.chat_message", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("sender_id")
                        .HasColumnType("integer");

                    b.Property<string>("text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("thread_id")
                        .HasColumnType("integer");

                    b.HasKey("id")
                        .HasName("chat_messages_pkey");

                    b.HasIndex("sender_id");

                    b.HasIndex("thread_id");

                    b.ToTable("chat_messages");
                });

            modelBuilder.Entity("ApiCoffeeTea.Data.chat_thread", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("id"));

                    b.Property<int>("client_id")
                        .HasColumnType("integer");

                    b.Property<int?>("consultant_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValueSql("'open'::character varying");

                    b.HasKey("id")
                        .HasName("chat_threads_pkey");

                    b.HasIndex("client_id");

                    b.HasIndex("consultant_id");

                    b.ToTable("chat_threads");
                });

            modelBuilder.Entity("ApiCoffeeTea.Data.coupon", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("id"));

                    b.Property<string>("code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("discount_type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal?>("min_total")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int?>("usage_limit")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("valid_from")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("valid_to")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("value")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("id")
                        .HasName("coupons_pkey");

                    b.HasIndex(new[] { "code" }, "coupons_code_key")
                        .IsUnique();

                    b.ToTable("coupons");
                });

            modelBuilder.Entity("ApiCoffeeTea.Data.order", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("id"));

                    b.Property<int>("address_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("payment_status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValueSql("'pending'::character varying");

                    b.Property<int>("status_id")
                        .HasColumnType("integer");

                    b.Property<decimal>("total")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("user_id")
                        .HasColumnType("integer");

                    b.HasKey("id")
                        .HasName("orders_pkey");

                    b.HasIndex("status_id");

                    b.HasIndex(new[] { "address_id" }, "ix_orders_address_id");

                    b.HasIndex(new[] { "user_id" }, "ix_orders_user_id");

                    b.ToTable("orders");
                });

            modelBuilder.Entity("ApiCoffeeTea.Data.order_item", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("id"));

                    b.Property<int>("order_id")
                        .HasColumnType("integer");

                    b.Property<int>("product_id")
                        .HasColumnType("integer");

                    b.Property<int>("qty")
                        .HasColumnType("integer");

                    b.Property<decimal>("unit_price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("id")
                        .HasName("order_items_pkey");

                    b.HasIndex("product_id");

                    b.HasIndex(new[] { "order_id" }, "ix_order_items_order_id");

                    b.ToTable("order_items");
                });

            modelBuilder.Entity("ApiCoffeeTea.Data.order_status", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("id")
                        .HasName("order_statuses_pkey");

                    b.HasIndex(new[] { "name" }, "order_statuses_name_key")
                        .IsUnique();

                    b.ToTable("order_statuses");
                });

            modelBuilder.Entity("ApiCoffeeTea.Data.payment", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("id"));

                    b.Property<decimal>("amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("method")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("order_id")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("paid_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("provider_txn_id")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("id")
                        .HasName("payments_pkey");

                    b.HasIndex("order_id");

                    b.ToTable("payments");
                });

            modelBuilder.Entity("ApiCoffeeTea.Data.product", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("id"));

                    b.Property<int?>("category_id")
                        .HasColumnType("integer");

                    b.Property<bool>("deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<string>("image_url")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("origin_country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("origin_region")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("processing")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("roast_level")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("sku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("id")
                        .HasName("products_pkey");

                    b.HasIndex("category_id");

                    b.HasIndex(new[] { "type" }, "ix_products_type");

                    b.HasIndex(new[] { "sku" }, "products_sku_key")
                        .IsUnique();

                    b.ToTable("products");
                });

            modelBuilder.Entity("ApiCoffeeTea.Data.product_detail", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("id"));

                    b.Property<string>("brewing_guide")
                        .HasColumnType("text");

                    b.Property<bool>("deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("flavor_notes")
                        .HasColumnType("text");

                    b.Property<string>("long_description")
                        .HasColumnType("text");

                    b.Property<string>("origin_details")
                        .HasColumnType("text");

                    b.Property<int>("product_id")
                        .HasColumnType("integer");

                    b.HasKey("id")
                        .HasName("product_details_pkey");

                    b.HasIndex(new[] { "product_id" }, "product_details_product_id_key")
                        .IsUnique();

                    b.ToTable("product_details");
                });

            modelBuilder.Entity("ApiCoffeeTea.Data.review", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("is_moderated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("product_id")
                        .HasColumnType("integer");

                    b.Property<int>("rating")
                        .HasColumnType("integer");

                    b.Property<string>("text")
                        .HasColumnType("text");

                    b.Property<int>("user_id")
                        .HasColumnType("integer");

                    b.HasKey("id")
                        .HasName("reviews_pkey");

                    b.HasIndex("product_id");

                    b.HasIndex("user_id");

                    b.ToTable("reviews");
                });

            modelBuilder.Entity("ApiCoffeeTea.Data.role", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("id"));

                    b.Property<bool>("deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("id")
                        .HasName("roles_pkey");

                    b.HasIndex(new[] { "name" }, "roles_name_key")
                        .IsUnique();

                    b.ToTable("roles");
                });

            modelBuilder.Entity("ApiCoffeeTea.Data.shipment", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("id"));

                    b.Property<string>("carrier")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("delivered_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("order_id")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("shipped_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("tracking_number")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("id")
                        .HasName("shipments_pkey");

                    b.HasIndex(new[] { "order_id" }, "shipments_order_id_key")
                        .IsUnique();

                    b.ToTable("shipments");
                });

            modelBuilder.Entity("ApiCoffeeTea.Data.user", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("middle_name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("password_hash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("role_id")
                        .HasColumnType("integer");

                    b.HasKey("id")
                        .HasName("users_pkey");

                    b.HasIndex("role_id");

                    b.HasIndex(new[] { "email" }, "ix_users_email");

                    b.HasIndex(new[] { "email" }, "users_email_key")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("article_product", b =>
                {
                    b.Property<int>("article_id")
                        .HasColumnType("integer");

                    b.Property<int>("product_id")
                        .HasColumnType("integer");

                    b.HasKey("article_id", "product_id")
                        .HasName("article_products_pkey");

                    b.HasIndex("product_id");

                    b.ToTable("article_products", (string)null);
                });

            modelBuilder.Entity("order_coupon", b =>
                {
                    b.Property<int>("order_id")
                        .HasColumnType("integer");

                    b.Property<int>("coupon_id")
                        .HasColumnType("integer");

                    b.HasKey("order_id", "coupon_id")
                        .HasName("order_coupons_pkey");

                    b.HasIndex("coupon_id");

                    b.ToTable("order_coupons", (string)null);
                });

            modelBuilder.Entity("ApiCoffeeTea.Data.address", b =>
                {
                    b.HasOne("ApiCoffeeTea.Data.user", "user")
                        .WithMany("addresses")
                        .HasForeignKey("user_id")
                        .IsRequired()
                        .HasConstraintName("addresses_user_id_fkey");

                    b.Navigation("user");
                });

            modelBuilder.Entity("ApiCoffeeTea.Data.article", b =>
                {
                    b.HasOne("ApiCoffeeTea.Data.article_category", "category")
                        .WithMany("articles")
                        .HasForeignKey("category_id")
                        .HasConstraintName("articles_category_id_fkey");

                    b.Navigation("category");
                });

            modelBuilder.Entity("ApiCoffeeTea.Data.audit_log", b =>
                {
                    b.HasOne("ApiCoffeeTea.Data.user", "user")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("audit_log_user_id_fkey");

                    b.Navigation("user");
                });

            modelBuilder.Entity("ApiCoffeeTea.Data.cart", b =>
                {
                    b.HasOne("ApiCoffeeTea.Data.product", "product")
                        .WithMany("carts")
                        .HasForeignKey("product_id")
                        .IsRequired()
                        .HasConstraintName("cart_product_id_fkey");

                    b.HasOne("ApiCoffeeTea.Data.user", "user")
                        .WithMany("carts")
                        .HasForeignKey("user_id")
                        .IsRequired()
                        .HasConstraintName("cart_user_id_fkey");

                    b.Navigation("product");

                    b.Navigation("user");
                });

            modelBuilder.Entity("ApiCoffeeTea.Data.category", b =>
                {
                    b.HasOne("ApiCoffeeTea.Data.category", "parent")
                        .WithMany("Inverseparent")
                        .HasForeignKey("parent_id")
                        .HasConstraintName("categories_parent_id_fkey");

                    b.Navigation("parent");
                });

            modelBuilder.Entity("ApiCoffeeTea.Data.chat_message", b =>
                {
                    b.HasOne("ApiCoffeeTea.Data.user", "sender")
                        .WithMany("chat_messages")
                        .HasForeignKey("sender_id")
                        .IsRequired()
                        .HasConstraintName("chat_messages_sender_id_fkey");

                    b.HasOne("ApiCoffeeTea.Data.chat_thread", "thread")
                        .WithMany("chat_messages")
                        .HasForeignKey("thread_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("chat_messages_thread_id_fkey");

                    b.Navigation("sender");

                    b.Navigation("thread");
                });

            modelBuilder.Entity("ApiCoffeeTea.Data.chat_thread", b =>
                {
                    b.HasOne("ApiCoffeeTea.Data.user", "client")
                        .WithMany("chat_threadclients")
                        .HasForeignKey("client_id")
                        .IsRequired()
                        .HasConstraintName("chat_threads_client_id_fkey");

                    b.HasOne("ApiCoffeeTea.Data.user", "consultant")
                        .WithMany("chat_threadconsultants")
                        .HasForeignKey("consultant_id")
                        .HasConstraintName("chat_threads_consultant_id_fkey");

                    b.Navigation("client");

                    b.Navigation("consultant");
                });

            modelBuilder.Entity("ApiCoffeeTea.Data.order", b =>
                {
                    b.HasOne("ApiCoffeeTea.Data.address", "address")
                        .WithMany("orders")
                        .HasForeignKey("address_id")
                        .IsRequired()
                        .HasConstraintName("orders_address_id_fkey");

                    b.HasOne("ApiCoffeeTea.Data.order_status", "status")
                        .WithMany("orders")
                        .HasForeignKey("status_id")
                        .IsRequired()
                        .HasConstraintName("orders_status_id_fkey");

                    b.HasOne("ApiCoffeeTea.Data.user", "user")
                        .WithMany("orders")
                        .HasForeignKey("user_id")
                        .IsRequired()
                        .HasConstraintName("orders_user_id_fkey");

                    b.Navigation("address");

                    b.Navigation("status");

                    b.Navigation("user");
                });

            modelBuilder.Entity("ApiCoffeeTea.Data.order_item", b =>
                {
                    b.HasOne("ApiCoffeeTea.Data.order", "order")
                        .WithMany("order_items")
                        .HasForeignKey("order_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("order_items_order_id_fkey");

                    b.HasOne("ApiCoffeeTea.Data.product", "product")
                        .WithMany("order_items")
                        .HasForeignKey("product_id")
                        .IsRequired()
                        .HasConstraintName("order_items_product_id_fkey");

                    b.Navigation("order");

                    b.Navigation("product");
                });

            modelBuilder.Entity("ApiCoffeeTea.Data.payment", b =>
                {
                    b.HasOne("ApiCoffeeTea.Data.order", "order")
                        .WithMany("payments")
                        .HasForeignKey("order_id")
                        .IsRequired()
                        .HasConstraintName("payments_order_id_fkey");

                    b.Navigation("order");
                });

            modelBuilder.Entity("ApiCoffeeTea.Data.product", b =>
                {
                    b.HasOne("ApiCoffeeTea.Data.category", "category")
                        .WithMany("products")
                        .HasForeignKey("category_id")
                        .HasConstraintName("products_category_id_fkey");

                    b.Navigation("category");
                });

            modelBuilder.Entity("ApiCoffeeTea.Data.product_detail", b =>
                {
                    b.HasOne("ApiCoffeeTea.Data.product", "product")
                        .WithOne("product_detail")
                        .HasForeignKey("ApiCoffeeTea.Data.product_detail", "product_id")
                        .IsRequired()
                        .HasConstraintName("product_details_product_id_fkey");

                    b.Navigation("product");
                });

            modelBuilder.Entity("ApiCoffeeTea.Data.review", b =>
                {
                    b.HasOne("ApiCoffeeTea.Data.product", "product")
                        .WithMany("reviews")
                        .HasForeignKey("product_id")
                        .IsRequired()
                        .HasConstraintName("reviews_product_id_fkey");

                    b.HasOne("ApiCoffeeTea.Data.user", "user")
                        .WithMany("reviews")
                        .HasForeignKey("user_id")
                        .IsRequired()
                        .HasConstraintName("reviews_user_id_fkey");

                    b.Navigation("product");

                    b.Navigation("user");
                });

            modelBuilder.Entity("ApiCoffeeTea.Data.shipment", b =>
                {
                    b.HasOne("ApiCoffeeTea.Data.order", "order")
                        .WithOne("shipment")
                        .HasForeignKey("ApiCoffeeTea.Data.shipment", "order_id")
                        .IsRequired()
                        .HasConstraintName("shipments_order_id_fkey");

                    b.Navigation("order");
                });

            modelBuilder.Entity("ApiCoffeeTea.Data.user", b =>
                {
                    b.HasOne("ApiCoffeeTea.Data.role", "role")
                        .WithMany("users")
                        .HasForeignKey("role_id")
                        .IsRequired()
                        .HasConstraintName("users_role_id_fkey");

                    b.Navigation("role");
                });

            modelBuilder.Entity("article_product", b =>
                {
                    b.HasOne("ApiCoffeeTea.Data.article", null)
                        .WithMany()
                        .HasForeignKey("article_id")
                        .IsRequired()
                        .HasConstraintName("article_products_article_id_fkey");

                    b.HasOne("ApiCoffeeTea.Data.product", null)
                        .WithMany()
                        .HasForeignKey("product_id")
                        .IsRequired()
                        .HasConstraintName("article_products_product_id_fkey");
                });

            modelBuilder.Entity("order_coupon", b =>
                {
                    b.HasOne("ApiCoffeeTea.Data.coupon", null)
                        .WithMany()
                        .HasForeignKey("coupon_id")
                        .IsRequired()
                        .HasConstraintName("order_coupons_coupon_id_fkey");

                    b.HasOne("ApiCoffeeTea.Data.order", null)
                        .WithMany()
                        .HasForeignKey("order_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("order_coupons_order_id_fkey");
                });

            modelBuilder.Entity("ApiCoffeeTea.Data.address", b =>
                {
                    b.Navigation("orders");
                });

            modelBuilder.Entity("ApiCoffeeTea.Data.article_category", b =>
                {
                    b.Navigation("articles");
                });

            modelBuilder.Entity("ApiCoffeeTea.Data.category", b =>
                {
                    b.Navigation("Inverseparent");

                    b.Navigation("products");
                });

            modelBuilder.Entity("ApiCoffeeTea.Data.chat_thread", b =>
                {
                    b.Navigation("chat_messages");
                });

            modelBuilder.Entity("ApiCoffeeTea.Data.order", b =>
                {
                    b.Navigation("order_items");

                    b.Navigation("payments");

                    b.Navigation("shipment");
                });

            modelBuilder.Entity("ApiCoffeeTea.Data.order_status", b =>
                {
                    b.Navigation("orders");
                });

            modelBuilder.Entity("ApiCoffeeTea.Data.product", b =>
                {
                    b.Navigation("carts");

                    b.Navigation("order_items");

                    b.Navigation("product_detail");

                    b.Navigation("reviews");
                });

            modelBuilder.Entity("ApiCoffeeTea.Data.role", b =>
                {
                    b.Navigation("users");
                });

            modelBuilder.Entity("ApiCoffeeTea.Data.user", b =>
                {
                    b.Navigation("addresses");

                    b.Navigation("carts");

                    b.Navigation("chat_messages");

                    b.Navigation("chat_threadclients");

                    b.Navigation("chat_threadconsultants");

                    b.Navigation("orders");

                    b.Navigation("reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
